"""add polygon_ticker to assets

Revision ID: 891cdd5a5445
Revises: 6ffc5c7d17e8
Create Date: 2026-06-23 13:58:26.033561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '891cdd5a5445'
down_revision: Union[str, Sequence[str], None] = '6ffc5c7d17e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('polygon_ticker' , sa.String(length=32) , nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('assets' , 'polygon_ticker')
